"""changes to models.py

Revision ID: 2227d88eb408
Revises: 7b79d12c1b05
Create Date: 2025-12-07 20:20:55.840445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2227d88eb408'
down_revision: Union[str, None] = '7b79d12c1b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner',
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('day', 'meal_id')
    )
    op.alter_column('favorites', 'meal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('favorites', 'created_at')
    op.alter_column('meals', 'ingredients',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meals', 'instructions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('meals', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.alter_column('meals', 'instructions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meals', 'ingredients',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('favorites', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.alter_column('favorites', 'meal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('planner')
    # ### end Alembic commands ###
